import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import 'rsuite/dist/rsuite-no-reset.min.css';
import { getServerSession } from 'next-auth';
import StoreProvider from '../../Provider/StoreProvider';
import SessionProvider from '../../Provider/AuthProvider';
import SideBar from '@/components/SideBar';
import { options } from '../../pages/api/auth/[...nextauth]';


const Montserrat = localFont({
  src: [
    {
      path: '../../public/fonts/Montserrat-Light.otf',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../../public/fonts/Montserrat-Regular.otf',
      weight: '600',
      style: 'normal',
    },
    {
      path: '../../public/fonts/Montserrat-bold.otf',
      weight: '800',
      style: 'normal',
    },
  ],
})
export const metadata: Metadata = {
  title: {
    absolute: "",
    default: 'my-next-project',
    template: " %s | next project"
  },
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession(options)
  return (
    <StoreProvider>
      <html lang="en">
        <body className={Montserrat.className}>
          <SessionProvider session={session}>
            {session ?
              <div className="flex">
                <div className='flex-1 h-screen'>
                  <SideBar />
                </div>
                <div className=' bg-greyShades-100 max-md:flex-[2] max-lg:flex-[3]  flex-[4] min-h-screen'>
                  {children}
                </div>
              </div>
              : <>
                {children}
              </>
            }
          </SessionProvider>
        </body>
      </html>
    </StoreProvider>
  )
}